code 3.7 02_compute_mean_std.py: 특징값 벡터의 평균과 표준편차 계산하기

In [ ]:
if __name__ == '__main__':
    feature_list = ['fbank', 'mfcc']
    
    for feature in feature_list:
        feat_scp = './%s/train_small/feats.scp' % (feature)
        out_dir = '/%s/train_small' % (feature)
        
        feat_mean = None
        feat_var = None
        total_frames = 0
        
        with open(feat_scp, mode = 'r') as file_feat:
            for i, line in enumerate(file_feat):
                parts = line.split()
                utterance_id = parts[0]
                feat_path = parts[1]
                num_frames = int(parts[2])
                num_dims = int(parts[3])
                
                feature = np.fromfile(feat_path, dtype = np.float32)
                feature = feature.reshape((num_frames, num_dims))
                
                if i == 0:
                    feat_mean = np.zeros(num_dims, np.float32)
                    feat_var = np.zeros(num_dims, np.float32)
                    
                total_frames += num_frames
                feat_mean += np.sum(feature, axis = 0)
                feat_var += np.sum(np.power(feature, 2), axis = 0)
                
        feat_mean /= total_frames
        feat_var = (feat_var / total_frames) - np.power(feat_mean, 2)
        feat_std = np.sqrt(feat_var)
        
        out_file = os.path.join(out_dir, 'mean_std.txt')
        print('Output file: %s' %(out_file))
        with open(out_file, mode = 'w') as file_o:
            file_o.write('mean\n')
            for i in range(np.size(feat_mean)):
                file_o.write('%e '% (feat_mean[i]))
            file_o.write('\n')
            for i in range(np.size(feat_var)):
                file_o.write('%e '% (feat_var[i]))
            file_o.write('\n')

250321
------------------------------------

In [ ]:
if __name__ == '__main__':
    feature_list = ['fbank', 'mfcc']
    
    for feature in feature_list:
        feat_file = os.path.join(os.getcwd(), feature, 'feats.scp') # feat_scp = './%s/train_small/feats.scp' % (feature)
        out_file = os.path.join(os.abspath('..'), feature, 'out.txt') # out_dir = './%s/train_small' % (feature)
        
        feat_mean = None
        feat_var = None
        total_frames = 0
        
        # with open(feat_scp, mode = 'r') as file_feat:
        for i, file in enumerate(feat_file): # for i, file in enumerate(file_feat):
            open(file, mode = 'r') as f:
                for line in f.readlines(): # 없어도 됨
                    parts = line.split() 
                    utterance_id = parts[0]
                    feat_path = parts[1]
                    num_frames = parts[2] #int(parts[2])
                    num_dims = parts[3] # int(parts[3])
                    
                    feature = np.fromfile(feat_path) # np.fromfile(feat_path, dtype = np.float32)
                    feature = np.array(feature).reshape((num_frames, num_dims)) # feature = feature.reshape(num_frames,num_dims)
                    
                    if i == 0:
                        feat_mean = 0 # feat_mean = np.zeros(num_dims, np.float32)
                        feat_var = 0 # feat_var = np.zeros(num_dims, np.float32)
                    else:
                        continue
                        
                    total_frames += num_frames
                    feat_mean += np.sum(features) # feat_mean += np.sum(feature, axis = 0)
                    feat_var += np.sum(np.power(features, 2)) # feat_var += np.sum(np.power(feature, 2), axis = 0)
                
                feat_mean /= total_frames
                feat_var = feat_var / total_frames - np.power(feat_mean, 2)
                # 제곱근을 취해서 표준편차 벡터 산출 
                # feat_std = np.sqrt(feat_var)
                
                # out_file = os.path.join(out_dir, 'mean_std.txt')
                print('Output file: %s' % (out_file))
                
                with open(out_file, mode = 'w') as out_file: # as file_o:
                    out_file.write('%s %s %d %d' % (utterance_id, file, feat_mean, feat_var))
                    # file_o.write('mean\n')
                    # for i in range(np.size(feat_mean)):
                    # file_o.write('%e ' % (feat_mean[i]))
                    # fie_o.write('\n')
                    # file_o.write('std\n')
                    # for i in range(np.size(feat_std)):
                    # file_o.write('%e ' % (feat_std[i]))
                    # file_o.write('\n')
                    

In [ ]:
if __name__ == '__main__':
    feature_list = ['fbank', 'mfcc']
    for feature in feature_list:
        feat_scp = './%s/train_small/feats.scp' % (feature)
        out_dir = './%s/train_small/' % (feature)
        
        feat_mean = None
        feat_var = None
        total_frames = 0
        
        with open(feat_scp, mode = 'r') as file_feat:
            for i, line in enumerate(file_feat):
                parts = line.split()
                utterance_id = parts[0]
                feat_path = parts[1]
                num_frames = int(parts[2])
                num_dims = int(parts[3])
                
                feature = np.fromfile(feat_path, 
                                     dtype = np.float32)
                
                feature = feature.reshape(num_frames, num_dims)
                
                if i == 0:
                    feat_mean = np.zeros(num_dims, np.float32)
                    feat_var = np.zeros(num_dims, np.float32)
                    
                total_frames += num_frames
                feat_mean += np.sum(feature, 
                                   axis = 0)
                feat_var += np.sum(np.power(feature, 2), axis = 0)
                
            feat_mean /= total_frames
            feat_var = (feat_var / total_frames) - np.power(feature, 2)
            feat_std = np.sqrt(feat_var)
            
            out_file = os.path.join(out_dir, 'mean_std.txt')
            print('Output file: %s' % (out_file))
            with open(out_file, mode = 'w') as file_o:
                file_o.write('mean\n')
                for i in range(np.size(feat_mean)):
                    file_o.write('%e ' % (feat_mean[i]))
                file_o.write('\n')
                file_o.write('std\n')
                for i in range(np.size(feat_std)):
                    file_o.write('%e ' % (feat_std[i]))
                file_o.write('\n')          

250322
------------------------------------

In [2]:
import numpy as np
feat_mean = np.zeros(13, np.float32)

In [3]:
feat_mean

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [5]:
Array = np.arange(39).reshape(3, 13)

In [6]:
feat_mean += np.sum(Array, axis = 0)

In [7]:
feat_mean

array([39., 42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75.],
      dtype=float32)

In [8]:
Array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]])

In [ ]:
if __name__ =='__main__':
    features = ['fbank', 'mfcc']
    for feature in feature:
        feat_list = os.path.join('../exp/data/test_data', feature, 'feats.scp') # feat_scp = './%s/train_small/feat.scp' % (feature)
        out_dir = os.path.join('../exp/data/test_data', feature) # out_dir = './%s/train_smal' % (feature)
        
    
        feat_mean = None
        feat_var = None
        total_frames = 0
        
        with open(feat_list, mode = 'r') as feat_info: # with open(feat_scp, mode = 'r') as file_feat:
                # for i, line in enumerate(file_feat):
                parts = line.split() 
                utt_ID = parts[0]
                path = parts[1]
                num_frames = parts[2] # num_frames = int(parts[2])
                num_dims = parts[3] # num_dims = int(parts[3])
                
                features = np.fromfile(path, dtype = np.float32)
                features = features.shape(num_frames, num_dims)
                
                
                # feat_mean = np.zeros(num_dims) 최초 파일 처리 뒤로
                # feat_var = np.zeros(num_dims) 최초 파일 처리 뒤로
                
                # for i, feature in features:     
                    if i == 0:
                        feat_mean = np.sum(features) # feat_mean = np.zeros(num_dims)
                        feat_var = np.sum(np.power(features, 2)) # feat_var = np.zeros(num_dims)
                    #else:
                     #   feat_mean += np.sum(features)
                     #  feat_var += np.sum(np.power(features, 2))
                
                    total_frames += num_frames
                    # feat_mean += np.sum(features, axis = 0)
                    # feat_var += np.sum(np.power(features, 2))
            
                feat_mean /= total_frames
                feat_var = feat_var / total_frames - np.power(feat_mean, 2)
                # feat_std = np.sqrt(feat_var)
            
                out_file = os.path.join(out_dir, #path, 
                                        'mean_std.txt')
                # print('Output file: %s' % (out_file))
                with open(out_file, mode = 'w') as f_out:
                    # f_out.write(path + '\n')
                    f_out.write('mean\n')
                    for i in range(np.size(feat_mean)):
                        f_out.write('%e ' % (feat_mean[i]))
                    f_out.write('\n')
                    f_out.write('std\n')
                    for i in range(np.size(feat_std)):
                        f_out.write('%e ' % (feat_std[i]))
                    f_out.write('\n')

In [25]:
feat_mean = None
feat_var = None

In [26]:
file1 = np.arange(0, 100, 2).reshape(10, 5)
file2 = np.arange(0, 200, 4).reshape(10, 5)
file3 = np.arange(0, 300, 6).reshape(10, 5)

In [27]:
files = [file1, file2, file3]

In [30]:
for (i, file) in enumerate(files):
    print(i, file)

0 [[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]
1 [[  0   4   8  12  16]
 [ 20  24  28  32  36]
 [ 40  44  48  52  56]
 [ 60  64  68  72  76]
 [ 80  84  88  92  96]
 [100 104 108 112 116]
 [120 124 128 132 136]
 [140 144 148 152 156]
 [160 164 168 172 176]
 [180 184 188 192 196]]
2 [[  0   6  12  18  24]
 [ 30  36  42  48  54]
 [ 60  66  72  78  84]
 [ 90  96 102 108 114]
 [120 126 132 138 144]
 [150 156 162 168 174]
 [180 186 192 198 204]
 [210 216 222 228 234]
 [240 246 252 258 264]
 [270 276 282 288 294]]


In [42]:
total_frames = 0
for (i, file) in enumerate(files):
    if i == 0:
        feat_mean = np.zeros(5)
        feat_var = np.zeros(5)
    total_frames += file.shape[0]
    feat_mean += np.sum(file, axis = 0)
    feat_var += np.sum(np.power(file, 2), axis = 0)
    print('feat_mean\n', feat_mean)
    print('feat_var\n', feat_var)

feat_mean = feat_mean / total_frames
feat_var = (feat_var / total_frames) - np.power(feat_mean, 2)
feat_std = np.sqrt(feat_var)

feat_mean
 [450. 470. 490. 510. 530.]
feat_var
 [28500. 30340. 32260. 34260. 36340.]
feat_mean
 [1350. 1410. 1470. 1530. 1590.]
feat_var
 [142500. 151700. 161300. 171300. 181700.]
feat_mean
 [2700. 2820. 2940. 3060. 3180.]
feat_var
 [399000. 424760. 451640. 479640. 508760.]
